[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "djinnml"
version = "1.1.2"
description = "Deep Jointly-Informed Neural Networks"
requires-python = ">=3.10, <4"
license = "BSD-3-Clause"
license-files = ["LICENSE", "NOTICE"]
authors = [ { name = "Ben Whewell", email = "ben.whewell@pm.me" } ]
keywords = ["regression", "neural networks", "pytorch"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "torch>=1.8",
    "scipy",
    "scikit-learn>=1.6",
]
readme = { file = "README.md", content-type = "text/markdown" }

[project.urls]
Repository = "https://github.com/bwhewe-13/DJINN"
Upstream = "https://github.com/LLNL/djinn"
Homepage = "https://github.com/bwhewe-13/DJINN"

[project.optional-dependencies]
testing = ["pytest>=7", "pytest-cov", "pandas"]
dev = [
    "pytest>=7",
    "pytest-cov",
    "pytest-xdist",
    "pandas",
    "black==26.1.0",
    "isort",
    "flake8",
    "pre-commit",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["djinn*"]
