"""
conftest.py — Shared fixtures for DJINN TF vs PyTorch comparison tests.

These fixtures are environment-agnostic: they only use numpy and sklearn,
so they work in both the tf-djinn and pt-djinn virtual environments.
"""

import shutil
from pathlib import Path

import numpy as np
import pytest
from sklearn.datasets import load_diabetes, load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# ---------------------------------------------------------------------------
# Random seed control
# ---------------------------------------------------------------------------

SEEDS = list(range(20))  # used for statistical tests
DEFAULT_SEED = 42


# ---------------------------------------------------------------------------
# Dataset fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def regression_data():
    """Provide a scaled single-output regression dataset.

    Returns
    -------
    tuple
        ``(X_train, X_test, y_train, y_test)`` arrays from the diabetes
        dataset.
    """
    X, y = load_diabetes(return_X_y=True)
    y = y.reshape(-1, 1)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=DEFAULT_SEED
    )
    scaler_x = MinMaxScaler()
    scaler_y = MinMaxScaler()
    X_train = scaler_x.fit_transform(X_train)
    X_test = scaler_x.transform(X_test)
    y_train = scaler_y.fit_transform(y_train)
    y_test = scaler_y.transform(y_test)
    return X_train, X_test, y_train, y_test


@pytest.fixture(scope="session")
def multiout_regression_data():
    """Provide a synthetic multi-output regression dataset.

    Returns
    -------
    tuple
        ``(X_train, X_test, y_train, y_test)`` arrays for a two-target task.
    """
    rng = np.random.default_rng(DEFAULT_SEED)
    X = rng.standard_normal((300, 6))
    # Two outputs with different linear relationships
    y = np.column_stack(
        [
            X[:, 0] * 2 + X[:, 1] - X[:, 2] + rng.standard_normal(300) * 0.1,
            X[:, 3] - X[:, 4] * 0.5 + rng.standard_normal(300) * 0.1,
        ]
    )
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=DEFAULT_SEED
    )
    return X_train, X_test, y_train, y_test


@pytest.fixture(scope="session")
def classification_data():
    """Provide an Iris multi-class classification split.

    Returns
    -------
    tuple
        ``(X_train, X_test, y_train, y_test)`` where targets are one-hot
        encoded.
    """
    X, y = load_iris(return_X_y=True)
    y_onehot = np.eye(3)[y]  # one-hot encode for DJINN
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_onehot, test_size=0.2, random_state=DEFAULT_SEED, stratify=y
    )
    return X_train, X_test, y_train, y_test


@pytest.fixture(scope="session")
def small_data():
    """Provide a small regression dataset for fast tests.

    Returns
    -------
    tuple
        ``(X_train, X_test, y_train, y_test)`` arrays for lightweight tests.
    """
    rng = np.random.default_rng(DEFAULT_SEED)
    X = rng.standard_normal((60, 4))
    y = (X[:, 0] + X[:, 1] ** 2).reshape(-1, 1)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=DEFAULT_SEED
    )
    return X_train, X_test, y_train, y_test


# ---------------------------------------------------------------------------
# Result collection helpers (used by both run_tf_tests.py / run_pt_tests.py)
# ---------------------------------------------------------------------------


def compute_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    """Compute standard regression metrics.

    Parameters
    ----------
    y_true : numpy.ndarray
        Ground-truth target values.
    y_pred : numpy.ndarray
        Predicted target values.

    Returns
    -------
    dict
        Dictionary containing ``mse``, ``mae``, and ``r2``.
    """
    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

    return {
        "mse": float(mean_squared_error(y_true, y_pred)),
        "mae": float(mean_absolute_error(y_true, y_pred)),
        "r2": float(r2_score(y_true, y_pred)),
    }


@pytest.fixture(scope="session", autouse=True)
def cleanup_test_output_files():
    """Remove DJINN model artifacts created during the test session.

    Yields
    ------
    None
        Runs test session first, then performs cleanup in teardown.
    """
    root = Path(__file__).resolve().parents[1]
    targets = [root, root / "tests"]

    # Patterns for artifacts generated by training/inference tests.
    tracked_patterns = [
        "djinn_model*",
        "djinn_model.pkl",
        "djinn_model_tree*",
        "nn_info_djinn*",
        "checkpoint",
        "*.ckpt",
        "*.ckpt.*",
    ]

    def list_matches(base_dir):
        matches = set()
        for pattern in tracked_patterns:
            matches.update(p.resolve() for p in base_dir.glob(pattern))
        return matches

    existing_by_dir = {base: list_matches(base) for base in targets if base.exists()}

    yield

    for base in targets:
        if not base.exists():
            continue

        existing = existing_by_dir.get(base, set())
        current = list_matches(base)
        created = [p for p in current if p not in existing]

        # Remove files first, then directories (deepest path first).
        files = sorted(
            [p for p in created if p.is_file()],
            key=lambda p: len(p.parts),
            reverse=True,
        )
        dirs = sorted(
            [p for p in created if p.is_dir()], key=lambda p: len(p.parts), reverse=True
        )

        for path in files:
            try:
                path.unlink()
            except FileNotFoundError:
                pass

        for path in dirs:
            shutil.rmtree(path, ignore_errors=True)
